### ISSUE TITLE
二楼功能，二楼界面隐藏在一楼之下，没有效果图中的下拉效果，是什么问题

### ISSUE THREAD

**Issue by 307295618** [AbnerMing888/HarmonyOsRefresh#100]

**Comment by AbnerMing888** [comment]
需要看下代码了，才能分析出啥问题了，不妨你先看看demo中案例

**Comment by 307295618** [comment]
> 需要看下代码了，才能分析出啥问题了，不妨你先看看demo中案例

你好，我就是下载的当前项目运行的，只不过依赖用的是远程的
![Dingtalk_20240724160614](https://github.com/user-attachments/assets/15a8e67a-1ba0-4de0-9def-a5ddfc9bb959)

**Comment by AbnerMing888** [comment]
这不是有下拉效果吗，目前是半楼效果

**Comment by AbnerMing888** [comment]
已经优化，请验证1.3.2版本
