### ISSUE TITLE
Crash：Controller not bound to component

### ISSUE THREAD

**Issue by tribelei** [AbnerMing888/HarmonyOsRefresh#102]
升级1.3.1，页面结构：
```
Scroll
    RefreshLayout
          Tabs
                 ListView
```

上下滑动几次后闪退，异常：
<img width="1007" alt="image" src="https://github.com/user-attachments/assets/8c857994-3056-41bf-84cd-b8e7e78a3fe1">

**Comment by AbnerMing888** [comment]
有一个案例Demo吗，辛苦可以发一下

**Comment by tribelei** [comment]
直接在项目代码里写的，之前用的1.2.2没问题，我暂时回退了，页面结构就是我上边写的那样...
