### ISSUE TITLE
itemHeaderLayout头部动态添加ListView的数据怎么处理？

### ISSUE THREAD

**Issue by d495988379** [AbnerMing888/HarmonyOsRefresh#103]
itemHeaderLayout 的布局目前不让传参数，如果想再头部请求接口后动态添加ListView的数据怎么处理？

**Comment by AbnerMing888** [comment]
可以传递啊
 itemHeaderLayout: ()=>{
          this.itemHeaderLayout()//括号里传递参数即可
        },

**Comment by d495988379** [comment]
this.itemHeaderLayout()//括号里传递参数即可
我传值以后 再itemHeaderLayout 方法里接收不到 是因为传值时使用this指向的问题吗？
