### ISSUE TITLE
希望上拉加载没有新的数据时，能够有一个全部加载完成的状态

### ISSUE THREAD

**Issue by cheng1128feng** [AbnerMing888/HarmonyOsRefresh#111]
希望上拉加载没有新的数据时，能够有一个全部加载完成的状态，不再触发onLoadMore，可以展示“没有更多数据了”或者“已加载全部”
![Uploading 微信图片_20240729162804.jpg…]()

**Comment by AbnerMing888** [comment]
有啊，控制器里isFooterNothing就可以控制，finishLoadMore(true)，也可以展示无数据，在LoadMoreFooterAttr属性里footerNothingText，可以更改展示文本

**Comment by cheng1128feng** [comment]
谢谢

**Comment by JasonYinH** [comment]
@cheng1128feng 最后你咋处理的，我这边一直可以加载    
![image](https://github.com/user-attachments/assets/2449f168-4b91-4b42-8e67-578c4c25b7bf)

**Comment by JasonYinH** [comment]
可以了
