### ISSUE TITLE
anber/Refresh的ListView，itemLayout的builder里，Row()等使用stateStyles ，点击按压没有变化。

### ISSUE THREAD

**Issue by liangdong9676** [AbnerMing888/HarmonyOsRefresh#112]
itemLayout的builder里，Row()不支持stateStyles ，点击没有变化。是被组件的listItemAttribute或者其它属性覆盖了吗？？

  @Styles
  normalStyles(): void{
    .backgroundColor($r("app.color.white"))
    .borderRadius(10)
  }

  @Styles
  clickStyles(): void{
    .backgroundColor($r("app.color.red"))
    .borderRadius(10)
  }

  @Builder
  itemLayout(): void {
    Column() {
      Text("测试")
    }
    .stateStyles({
      normal: this.normalStyles,
      clicked: this.clickStyles,
    }).width("100%")
    .onClick(() => {
        showDialogOneButton("正在开发中");
    });
  }

**Comment by AbnerMing888** [comment]
支持啊，在使用@builder时，看下是否是this指向，如果指向不对，就把当前this传进去，（_this:你的类），使用_this

**Comment by liangdong9676** [comment]
不用this，就是在里面直接用这样也不行。但是奇怪的是stateStyles的normal生效了，其它的clicked，pressed等都不生效。

@Builder
  itemLayout(): void {
    Column() {
      Text("测试一下按压有没有效果")
        .fontColor(Color.Black)
        .fontSize(16)
        .height(100)
    }
    .stateStyles({
      normal: {
        .backgroundColor(Color.Blue)
        .borderRadius(10)
      },
      clicked: {
        .backgroundColor(Color.Green)
        .borderRadius(10)
      },
    }).width("100%")
    .onClick(() => {
      showDialogOneButton("正在开发中");
    });
  }

**Comment by AbnerMing888** [comment]
好的，我看一下

**Comment by XuMengren** [comment]
@liangdong9676 问题解决了吗

**Comment by liangdong9676** [comment]
> @liangdong9676 问题解决了吗

1.3.3版本是不行的，等作者更新版本吧

**Comment by liangdong9676** [comment]
> 好的，我看一下

1.3.7版本了，item的 stateStyles按压反馈效果，还是不行哦
