### ISSUE TITLE
GridView设置GridAttr的背景颜色没有效果

### ISSUE THREAD

**Issue by lucileu** [AbnerMing888/HarmonyOsRefresh#113]
GridView({
      controller: this.controller,
      items: this.recommendProxyList,
      itemLayout: (item, index) => this.RecommendItemLayout(item, index),
      itemHeaderLayout: () => {
        this.RecommendHeaderLayout()
      },
      isLazyData: false,
      gridAttribute: (g) => {
        g.rowsGap = 10 //设置行间距
        g.columnsGap = 10
        g.columnsTemplate = '1fr 1fr 1fr 1fr'
        g.padding = {bottom: 10}
        g.backgroundColor = Color.Red
      },
      onRefresh: () => {
        //下拉刷新
        this.onRefresh()
      },
      onLoadMore: () => {
        //上拉加载
        this.onLoadMore()
      }
    }).padding({left: 10, right: 10})
gridAttribute设置backgroundColor没有效果

**Comment by AbnerMing888** [comment]
我的问题我的问题，下个版本修复

**Comment by yushuaigh** [comment]
gridAttribute希望能支持动态设置每个item所占宽度，目前功能设置了会对全部item生效。但是无法给某个item设置。无法获取到当前item对象或者每个item下标
