### ISSUE TITLE
侧滑按钮传参只有一个 index，在 Group 的视图下，如何获取 Group 的 section

### ISSUE THREAD

**Issue by chen570075003** [AbnerMing888/HarmonyOsRefresh#114]
侧滑按钮传参只有一个 index，在 Group 的视图下，还需要一个 Group 的 section。比如：
header0
{0,0}
{0,1}
{0,2}
--------
header1
{1,0}
{1,1}
{1,2}
{1,3}

**Comment by chen570075003** [comment]
貌似是分组视图跟侧滑按钮不能同时存在，求大佬兼容一下😷

**Comment by AbnerMing888** [comment]
好的

**Comment by AbnerMing888** [comment]
下个版本可以使用如下：
groupSwipeRightMenuLayout: (parentPosition: number, index: number) => {
          //分组侧滑
        }
