### ISSUE TITLE
ListView刷新或者加载状态不同显示不同的头部文案以及尾部也是一样的

### ISSUE THREAD

**Issue by artillerymans** [AbnerMing888/HarmonyOsRefresh#115]
![image](https://github.com/user-attachments/assets/27e4e1c1-56cd-4c23-b929-c8f3888d2494)
我zhegy这样获取一直都是状态一直都是3，
我应该怎么获取

**Comment by artillerymans** [comment]
![image](https://github.com/user-attachments/assets/2e972e11-2f8b-4361-9b69-870dbc863c0d)
一直打印出来都是3

**Comment by AbnerMing888** [comment]
你接收的蚕食应该是：status: RefreshLayoutStatusModel

**Comment by AbnerMing888** [comment]
你接收的参数应该是：status: RefreshLayoutStatusModel

**Comment by artillerymans** [comment]
> 你接收的参数应该是：status: RefreshLayoutStatusModel

这个状态我可以主动获取吗？从什么地方获取的，我一开始是按照demo中在@Builder中接收但是里面的数据也是没有变化的
