### ISSUE TITLE
上拉&下拉gif动图自定义

### ISSUE THREAD

**Issue by sacrifice123** [AbnerMing888/HarmonyOsRefresh#127]
1、自定义上拉刷新的loading gif动图，但是gif图的尺寸大小在RefreshHeaderAttr属性里看到设置的地方
2、下拉刷新的动图好像没法通过LoadMoreFooterAttr属性自定义设置

**Comment by AbnerMing888** [comment]
你是想自己自定义，还是修改默认的，默认的没暴露，下个版本我暴露出去
