### ISSUE TITLE
支持lottie吗刷新头

### ISSUE THREAD

**Issue by JasonYinH** [AbnerMing888/HarmonyOsRefresh#129]

**Comment by JasonYinH** [comment]
![image](https://github.com/user-attachments/assets/c5b5cbff-c8b2-4481-a6ae-a7957a5ed8dc)
zhiji直接报错

**Comment by AbnerMing888** [comment]
你把this，以参数的形式传递进去，验证下：
footerLoadLayout(_this:你的当前类,model: LoadMoreLayoutStatusModel) {
}

**Comment by JasonYinH** [comment]
![image](https://github.com/user-attachments/assets/553cdd2d-a75c-41d4-838a-a8b7f7308bc1)
![image](https://github.com/user-attachments/assets/65b78fe0-3cf2-486a-b2db-ec69044bc52f)

**Comment by JasonYinH** [comment]
![image](https://github.com/user-attachments/assets/3deabade-0577-4785-b8f0-36b3c17bef31)
要feng疯了
