### ISSUE TITLE
和顶部控件重叠了  上拉加载也用不了

### ISSUE THREAD

**Issue by yuanduyua** [AbnerMing888/HarmonyOsRefresh#13]
<img width="254" alt="微信图片_20240516104731" src="https://github.com/AbnerMing888/HarmonyOsRefresh/assets/12746094/62a82925-e7ac-4912-a9b4-8b6286cff1f1">

**Comment by yuanduyua** [comment]
api11 用的模拟器

**Comment by yuanduyua** [comment]
build() {

    Column() {
      Text('我是title')
        .fontSize(50)
        .textAlign(TextAlign.Center)
        .fontWeight(FontWeight.Bold).height(60)
        .backgroundColor(Color.Blue)
        .width('100%')

      ListView({
        items: this.list, //数据源 数组
        itemLayout: (item: string, index) => this.itemLayout(item, index), //条目布局
        controller: this.controller, //控制器，负责关闭下拉和上拉
        onRefresh: () => {
          //下拉刷新
          this.controller.finishRefresh() //关闭下拉刷新
        },
        onLoadMore: () => {
          //上拉加载
          this.controller.finishLoadMore() //关闭上拉加载
        }
      }).backgroundColor(Color.Pink)
    }.width('100%').height('100%').padding({top:35})

  }

**Comment by AbnerMing888** [comment]
ListView不要直接在后边添加属性，在大括号里添加，你把.backgroundColor(Color.Pink)去掉！

**Comment by yuanduyua** [comment]
build() {
    Column() {
      Text().height(35)
      Text('我是title')
        .fontSize(50)
        .textAlign(TextAlign.Center)
        .fontWeight(FontWeight.Bold)
        .height(60)
        .backgroundColor(Color.Blue)
        .width('100%')
      ListView({
        items: this.list, //数据源 数组
        itemLayout: (item: string, index) => this.itemLayout(item, index), //条目布局
        controller: this.controller, //控制器，负责关闭下拉和上拉
        onRefresh: () => {
          //下拉刷新
          this.controller.finishRefresh() //关闭下拉刷新
        },
        onLoadMore: () => {
          //上拉加载
          this.controller.finishLoadMore() //关闭上拉加载
        }
      })
    }

  }
<img width="241" alt="微信图片_20240516153030" src="https://github.com/AbnerMing888/HarmonyOsRefresh/assets/12746094/3c49cd4e-895f-4715-95a0-7eea3a7221d4">

**Comment by yuanduyua** [comment]
版本是"@abner/refresh": "^1.0.8"

**Comment by AbnerMing888** [comment]
@Entry
@Component
struct ListViewUpAndDownPage {
  @State controller: RefreshController = new RefreshController() //刷新控制器
  @State array: Array<number> = []

  aboutToAppear() {
    for (let i = 0; i < 50; i++) {
      this.array.push(i)
    }
  }

  /**
   * Author:AbnerMing
   * Describe:条目布局
   * @param item  数据对象
   * @param index  数据索引
   */
  @Builder
  itemLayout(item: Object, index: number): void {
    Text("测试数据" + index)
      .width("95%")
      .height(50)
      .margin(10)
      .textAlign(TextAlign.Center)
      .border({ width: 1, color: Color.Pink })
  }

  build() {
    Column() {
      Text('我是title')
        .fontSize(50)
        .textAlign(TextAlign.Center)
        .fontWeight(FontWeight.Bold)
        .height(60)
        .backgroundColor(Color.Blue)
        .width('100%')
      ListView({
        items: this.array, //数据源 数组
        itemLayout: (item, index) => this.itemLayout(item, index),
        controller: this.controller, //控制器，负责关闭下拉和上拉
        isLazyData: false,
        onRefresh: () => {
          //下拉刷新
          setTimeout(() => {
            this.controller.finishRefresh();
          }, 1000)
        },
        onLoadMore: () => {
          //上拉加载
          setTimeout(() => {
            this.controller.finishLoadMore();
          }, 1000)
        }
      })
    }
  }
}

**Comment by AbnerMing888** [comment]
你试试上面的代码

**Comment by yuanduyua** [comment]
<img width="266" alt="微信图片_20240516161845" src="https://github.com/AbnerMing888/HarmonyOsRefresh/assets/12746094/5c5a8fde-1614-4932-907b-de89214d9938">
不知道为啥我的就是这样显示

**Comment by AbnerMing888** [comment]
你Api几？

**Comment by AbnerMing888** [comment]
匪夷所思了，还真没有人提像你这样的问题

**Comment by AbnerMing888** [comment]
匪夷所思了，还真没有人遇到过这样的问题

**Comment by AbnerMing888** [comment]
你是拿着我的这个页面，原封不动的测试的吗

**Comment by yuanduyua** [comment]
"name": "default",
        "signingConfig": "default",
        "compileSdkVersion": "4.1.0(11)",
        "compatibleSdkVersion": "4.1.0(11)",
        "runtimeOS": "HarmonyOS"

**Comment by yuanduyua** [comment]
harmonyOS NEXT Developer Preview2

**Comment by AbnerMing888** [comment]
你把你完整的页面测试代码发来

**Comment by yuanduyua** [comment]
import { ListView, RefreshController } from '@app/refresh';

@Entry
@Component
struct TestPage {
  @State controller: RefreshController = new RefreshController() //刷新控制器，声明全局变量
  @State list: Array<string> = []

  aboutToAppear(): void {
    for (let i = 0; i < 50; i++) {
      this.list.push('======' + i)
    }
  }

  build() {
    Column() {
      Text('我是title')
        .fontSize(50)
        .textAlign(TextAlign.Center)
        .fontWeight(FontWeight.Bold)
        .height(60)
        .backgroundColor(Color.Blue)
        .width('100%')

      ListView({
        items: this.list, //数据源 数组
        itemLayout: (item: string, index) => this.itemLayout(item, index), //条目布局
        controller: this.controller, //控制器，负责关闭下拉和上拉
        onRefresh: () => {
          //下拉刷新
          this.controller.finishRefresh() //关闭下拉刷新
        },
        onLoadMore: () => {
          //上拉加载
          this.controller.finishLoadMore() //关闭上拉加载
        }
      })
    }

  }

  @Builder
  itemLayout(item: string, index: number) {
    Text('==============' + index).height(60)
  }
}

**Comment by AbnerMing888** [comment]
![Uploading Screenshot_2024-05-16T164821.png…]()

**Comment by AbnerMing888** [comment]
![Screenshot_2024-05-16T164821](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/37609363/738eb4bb-9f96-47e4-b078-23291a73ce4b)

**Comment by AbnerMing888** [comment]
没问题的，还有你语法多练练，上面的代码是有问题的，我给你改了几处：
@Entry
@Component
struct TestPage {
  @State controller: RefreshController = new RefreshController() //刷新控制器，声明全局变量
  @State list: Array<number> = []

  aboutToAppear(): void {
    for (let i = 0; i < 50; i++) {
      this.list.push(i)
    }
  }

  build() {
    Column() {
      Text('我是title')
        .fontSize(50)
        .textAlign(TextAlign.Center)
        .fontWeight(FontWeight.Bold)
        .height(60)
        .backgroundColor(Color.Blue)
        .width('100%')

      ListView({
        items: this.list, //数据源 数组
        itemLayout: (item: Object, index) => this.itemLayout(item, index), //条目布局
        controller: this.controller, //控制器，负责关闭下拉和上拉
        onRefresh: () => {
          //下拉刷新
          this.controller.finishRefresh() //关闭下拉刷新
        },
        onLoadMore: () => {
          //上拉加载
          this.controller.finishLoadMore() //关闭上拉加载
        }
      })
    }
  }

  @Builder
  itemLayout(item: Object, index: number) {
    Text('==============' + index).height(60)
  }
}

**Comment by yuanduyua** [comment]
很神奇

**Comment by AbnerMing888** [comment]
我知道，到github中它转义了

**Comment by AbnerMing888** [comment]
`@Entry
@Component
struct TestPage {
  @State controller: RefreshController = new RefreshController() //刷新控制器，声明全局变量
  @State list: Array<number> = []

  aboutToAppear(): void {
    for (let i = 0; i < 50; i++) {
      this.list.push(i)
    }
  }

  build() {
    Column() {
      Text('我是title')
        .fontSize(50)
        .textAlign(TextAlign.Center)
        .fontWeight(FontWeight.Bold)
        .height(60)
        .backgroundColor(Color.Blue)
        .width('100%')

      ListView({
        items: this.list, //数据源 数组
        itemLayout: (item: Object, index) => this.itemLayout(item, index), //条目布局
        controller: this.controller, //控制器，负责关闭下拉和上拉
        onRefresh: () => {
          //下拉刷新
          this.controller.finishRefresh() //关闭下拉刷新
        },
        onLoadMore: () => {
          //上拉加载
          this.controller.finishLoadMore() //关闭上拉加载
        }
      })
    }
  }

  @Builder
  itemLayout(item: Object, index: number) {
    Text('==============' + index).height(60)
  }
}`

**Comment by AbnerMing888** [comment]
上边的Array也是，这里评论发代码转义了

**Comment by yuanduyua** [comment]
所以现在到底是改哪里  你那正常 我这还是遮住了    有点懵

**Comment by AbnerMing888** [comment]
你下载下demo，安装到你模拟器或者手机里看下是否有问题：https://vipandroid-image.oss-cn-beijing.aliyuncs.com/harmony/refresh/refresh.hap

**Comment by yuanduyua** [comment]
demo没问题

**Comment by yuanduyua** [comment]
解决啦  我的错我的错     还集成着一个最早的版本 我说怎么有的属性没有呢   感谢大佬

**Comment by AbnerMing888** [comment]
解决了就好~

**Comment by zhaichenxiao-github** [comment]
不能添加属性设置padding，margin，layoutWeight这些属性怎么办

**Comment by WallaceYou** [comment]
怎么解决的？我也遇到了一样的问题
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/15206765/e8a6923f-4e9c-4905-bcac-6de61843b16f)
