### ISSUE TITLE
请问怎么控制刷新的高度

### ISSUE THREAD

**Issue by kongweibo-yy** [AbnerMing888/HarmonyOsRefresh#135]
请问怎么控制刷新下拉的高度呢，每次刷新和加载都可以一直向上或者向下啦，数据都看不见了还可以进行拉，为什么控制的RefreshHeaderAttr的高度是刷新头内容的显示。而不是刷新头组件可下拉的高度呢。

**Comment by Simplerd** [comment]
同问上诉下拉刷新阻尼高度问题，目前遇到的情况是可以一直下拉刷新头部移除至屏幕外了

**Comment by kongweibo-yy** [comment]
来个大佬解惑一下吧，求求各位大佬了

**Comment by AbnerMing888** [comment]
isScrollSpring:false，可以控制阻尼高度

**Comment by Simplerd** [comment]
> isScrollSpring:false，可以控制阻尼高度
感谢作者解答🤝
