### ISSUE TITLE
添加相对复杂的header和item，在返回上一个页面的时候会造成UI卡顿

### ISSUE THREAD

**Issue by cqli** [AbnerMing888/HarmonyOsRefresh#136]
![Uploading 卡顿.png…]()

**Comment by cqli** [comment]
![卡顿](https://github.com/user-attachments/assets/20a1c5c3-0db7-4fe3-b278-0e765c905d05)

**Comment by cqli** [comment]
同样的item使用官方grid、list 虽然也有AppDeadlineMissed，但是没有明显卡顿

**Comment by cqli** [comment]
1.Inappropriate state management. Keep the sum of the following within 30 for each session: number of items to be updated + number of items to be laid out + number of items to be rendered; 2.Too many property changes in the dirty component. Keep the number of properties to be updated per frame within 300.

item有一张图片，两行文字，使用组件复用也不行

**Comment by AbnerMing888** [comment]
本身就是基于官方封装的，有一个简单的Demo吗，我可以看下
