### ISSUE TITLE
刷新数据问题

### ISSUE THREAD

**Issue by zh793060640** [AbnerMing888/HarmonyOsRefresh#15]
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/18716654/be1887ff-ea55-475f-a1cf-51273fd1df28)

刷新输入，先delete，然后在添加，数据就会有问题

**Comment by AbnerMing888** [comment]
收到，1.0.9已做修复，增加删除回调，如果需要删除后立马添加数据，可在回调后在添加，可解决问题：
_this.dataSource.deleteAll(() => {
              _this.dataSource.pushDataArray([300, 301, 302])
            })
