### ISSUE TITLE
Listview如何设置外边距内边距权重等

### ISSUE THREAD

**Issue by zhaichenxiao-github** [AbnerMing888/HarmonyOsRefresh#16]
![1715932135636](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/68092312/d3295a9f-fa20-4a2f-b975-736d77b45323)
这种情况底部的加载显示不出来

**Comment by AbnerMing888** [comment]
加载不出来吗？

**Comment by zhaichenxiao-github** [comment]
是的下拉加载我这显示不出来

**Comment by zhaichenxiao-github** [comment]
是的下拉加载我这显示不出来

**Comment by AbnerMing888** [comment]
内外边距在1.1.2版本增加
