### ISSUE TITLE
当listview使用的对象包含protobuf对象时，会出现闪退

### ISSUE THREAD

**Issue by ant074** [AbnerMing888/HarmonyOsRefresh#161]
当listview使用的对象包含protobuf对象时，会出现闪退
![image](https://github.com/user-attachments/assets/46710954-085a-4a40-a564-6e546378623f)
![image](https://github.com/user-attachments/assets/35e6b827-e955-4d11-a4cc-49ba83e01a76)
问题出现在JSON.stringify使用上，
当修改为o26.toString()时，不再闪退。建议去掉JSON

**Comment by AbnerMing888** [comment]
为数据源每个数组项生成唯一且持久的键值，考虑到唯一性，官方也是使用的JSON.stringify(item)，如果改成toString()，特别是item是对象的时候，很难保障唯一性。
我看下如何兼容吧

**Comment by ant074** [comment]
那能否考虑将key增加自定义生成，释放给业务端呢？

**Comment by AbnerMing888** [comment]
在ForEach中，抛给业务层难，不像Android那样简单，我记得我定义了一个属性，isKeyGeneratorIndex，你设置为true试试，取得是当前的索引作为key

**Comment by ant074** [comment]
isKeyGeneratorIndex=true设置是能避开这个问题的，但存在UI更新问题，当然也是可以使用splice先删后加，操作上有点变形

**Comment by AbnerMing888** [comment]
UI更新问题，在有数据操作时，需要重置所有子组件的index索引，重置完就没问题了，其实官方也是这么搞【手动捂脸】
