### ISSUE TITLE
如何通过代码调下拉刷新

### ISSUE THREAD

**Issue by WallaceYou** [AbnerMing888/HarmonyOsRefresh#17]
如题，比如一进入页面就自动下拉刷新，再比如某个时机做完一些逻辑需要手动调用刷新一下？

**Comment by AbnerMing888** [comment]
这个，我会在下一个版本中增加，请关注最新的版本，不出意外应该是1.1.1或者1.1.2版本

**Comment by AbnerMing888** [comment]
功能已经增加，待升级后验证，使用控制器控制即可：this.controller.autoRefresh()，进入页面就在aboutToAppear方法里调用，其他某个时机也是调用autoRefresh()，就会下拉刷新，执行onRefresh回调方法。

**Comment by WallaceYou** [comment]
收到，运用项目时发现新的问题：https://github.com/AbnerMing888/HarmonyOsRefresh/issues/21
大佬有空帮忙看下
