### ISSUE TITLE
大佬，跟tabs的吸顶效果能实现在顶部刷新么?

### ISSUE THREAD

**Issue by 529523346** [AbnerMing888/HarmonyOsRefresh#18]
感觉一般产品的做法都是在顶部刷新，然后上拉加载交由各个item控制，请问这种有办法实现么
<img width="297" alt="image" src="https://github.com/AbnerMing888/HarmonyOsRefresh/assets/20179788/148cae34-dde3-4dce-897f-d3b60a681709">

**Comment by AbnerMing888** [comment]
有具体效果吗，或者哪个App，你说下，我可以看下

**Comment by 529523346** [comment]
> 有具体效果吗，或者哪个App，你说下，我可以看下

就是类似于这中效果，因为有些场景顶部数据也需要更新，所以把刷新放在顶部，然后会同步刷新当前选中的列表数据
<img width="646" alt="image" src="https://github.com/AbnerMing888/HarmonyOsRefresh/assets/20179788/677a72c8-460e-4035-99a7-aeda6eba46a4">
