### ISSUE TITLE
ListView列表空数据时无法下拉刷新

### ISSUE THREAD

**Issue by actionbar** [AbnerMing888/HarmonyOsRefresh#180]
@State data: String[] = [];
controller: RefreshController = new RefreshController() //刷新控制器，声明全局变量 
dataSource: RefreshDataSource = new RefreshDataSource() //数据懒加载操作对象，执行数据增删改查

aboutToAppear(): void {   
this.dataSource.initData(this.data);   
this.controller.autoRefresh(true); 
}

**Comment by AbnerMing888** [comment]
可以直接拿到状态的
`
 @Builder
  headerRefreshLayout(model: RefreshLayoutStatusModel) {

}
`

**Comment by AbnerMing888** [comment]
我测试了一下，空数据时，是可以下拉和上拉的啊

**Comment by actionbar** [comment]
> 我测试了一下，空数据时，是可以下拉和上拉的啊
这样子的时候确实没法手动下拉刷新
`
ListView({
   lazyDataSource: this.dataSource,
   itemLayout: (item: object, index) => {
     this.itemLayout(item, index)
   }, //条目布局
   controller: this.controller, //控制器，负责关闭下拉和上拉
   onRefresh: () => {
     this.reloadData();
   },
   onLoadMore: () => {
     this.controller.finishLoadMore(false)
   },
   lazyCachedCount: 4
 })
   .backgroundColor('#f5f5f5')
   .width('100%')
   .height('100%')
   .flexShrink(1)

`

**Comment by actionbar** [comment]
> 我测试了一下，空数据时，是可以下拉和上拉的啊
很好更新到，1.3.7后没有这个问题了
