### ISSUE TITLE
关于刷新回调的问题

### ISSUE THREAD

**Issue by lingjianglin** [AbnerMing888/HarmonyOsRefresh#181]
通过controller 的 getRefreshLayoutStatus 可以得到刷新的状态，但是我想要知道 何时 是 Pulling refreshing 等等，可以实时给一个刷新状态的回调

**Comment by AbnerMing888** [comment]
可以直接拿到状态的

@ Builder
headerRefreshLayout(model: RefreshLayoutStatusModel) {

}

**Comment by lingjianglin** [comment]
> 可以直接拿到状态的
> 
> @ Builder headerRefreshLayout(model: RefreshLayoutStatusModel) {
> 
> }

不行的，我用这个 mode.status 一直是Finish  = 3
