### ISSUE TITLE
ListView怎么在加载完毕后立马滚动到最下面

### ISSUE THREAD

**Issue by udoubi** [AbnerMing888/HarmonyOsRefresh#184]
比如聊天界面，进入消息页面，消息加载完立马滚动到最下面，显示最新的消息

<img width="603" alt="image" src="https://github.com/user-attachments/assets/1a27fcef-d9e3-424f-9a9c-f1a9131c61eb">

我试了立即调用scrollToIndex是没效果的，需要一个延时，但是效果不好，能有其他方法吗

**Comment by AbnerMing888** [comment]
可以试试：this.scroller?.scrollEdge(Edge.Bottom)
