### ISSUE TITLE
数据源的数据如果存在循环引用会崩溃

### ISSUE THREAD

**Issue by udoubi** [AbnerMing888/HarmonyOsRefresh#185]
<img width="857" alt="image" src="https://github.com/user-attachments/assets/fefd9899-d630-4fcb-a423-c43be0a857aa">
这里的序列化 的数据如果存在循环引用会崩溃，能不能提供一个自定义key的方法

**Comment by AbnerMing888** [comment]
数据是一个循环，每个item对应的唯一的Key，暂时无法抛给业务层，不过有一个属性，isKeyGeneratorIndex，你设置为true试试

**Comment by udoubi** [comment]
isKeyGeneratorIndex设置为true，那就是用序列号做key，数据的插入删除会有问题
