### ISSUE TITLE
异步请求数据后调用finishRefresh 无效

### ISSUE THREAD

**Issue by 529523346** [AbnerMing888/HarmonyOsRefresh#19]
大佬帮忙看下
<img width="1008" alt="image" src="https://github.com/AbnerMing888/HarmonyOsRefresh/assets/20179788/4948daef-6f6e-4f73-8243-54f57c5a6ce5">
<img width="318" alt="image" src="https://github.com/AbnerMing888/HarmonyOsRefresh/assets/20179788/239637f8-2e2b-4f11-bc5f-1844822f23a3">

**Comment by 529523346** [comment]
> 大佬帮忙看下

<img width="1008" alt="image" src="https://github.com/AbnerMing888/HarmonyOsRefresh/assets/20179788/4948daef-6f6e-4f73-8243-54f57c5a6ce5">

**Comment by AbnerMing888** [comment]
第一、排查下控制器变量是否使用@State来修饰了。
第二、如果第一中修饰了，那问题就是this指向问题

**Comment by 529523346** [comment]
> 第一、排查下控制器变量是否使用@State来修饰了。 第二、如果第一中修饰了，那问题就是this指向问题

没有哇，就正常new了个对象
<img width="1125" alt="image" src="https://github.com/AbnerMing888/HarmonyOsRefresh/assets/20179788/797fe948-f026-43b5-afb8-721998bd0e10">

**Comment by 529523346** [comment]
> > 第一、排查下控制器变量是否使用@State来修饰了。 第二、如果第一中修饰了，那问题就是this指向问题
> 
> 没有哇，就正常new了个对象 <img alt="image" width="1125" src="https://private-user-images.githubusercontent.com/20179788/332246260-797fe948-f026-43b5-afb8-721998bd0e10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNTUwMzcsIm5iZiI6MTcxNjI1NDczNywicGF0aCI6Ii8yMDE3OTc4OC8zMzIyNDYyNjAtNzk3ZmU5NDgtZjAyNi00M2I1LWFmYjgtNzIxOTk4YmQwZTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAxMjUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMmZhZGNmZDUyMDk3NzRkMTg3ZmI5OWM3ZGIyOGRhMzM4YmQxNzIyZmEwOTkyZTUzNmU2NzAzNTczOTdmM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3muIQCMHzLQcEo_CnO2WUAU0ZjDjJi8sA7A_2x_5YyQ">

哦哦，要用@state修饰是吧，知道了，大佬
