### ISSUE TITLE
提交市场被拒绝，说是系统出现JsCrash异常啥的

### ISSUE THREAD

**Issue by mm2m123** [AbnerMing888/HarmonyOsRefresh#194]
（1）兼容性：
①崩溃：系统出现JsCrash异常,原因: Generated by HiviewDFX@OpenHarmony___at anonymous (entry|@abner/refresh|1.3.5|src/main/ets/RefreshLayout.js:747:1)（Mate 60 Pro）；
②任务连续：折叠屏支架态检测由折叠态切换至支架态时出现任务中断；折叠屏检测由展开态切换至折叠态时出现任务中断（Mate X5）。
（2）稳定性：Js Crash：Error name:Error
Error message:Controller not bound to component.
Error code:100004
Stacktrace:
Cannot get SourceMap info, dump raw stack:
at anonymous (entry|@abner/refresh|1.3.5|src/main/ets/RefreshLayout.js:747:1)（Mate 60）。
测试环境：Wi-Fi联网、中文环境、Mate 60 Pro、Mate X5、Mate 60。

**Comment by AbnerMing888** [comment]
提交市场拒绝？我们的应用已经上架了，不过问题已关注，我排查下原因

**Comment by AbnerMing888** [comment]
错误信息只跟踪到RefreshLayout？具体的业务层没有跟踪到吗？不应该吧，大概率是业务层的错误导致的

**Comment by mm2m123** [comment]
> 错误信息只跟踪到RefreshLayout？具体的业务层没有跟踪到吗？不应该吧，大概率是业务层的错误导致的

具体的业务层没有跟踪到，只跟踪到RefreshLayout。
今儿上午上线成功了。
但我没更新库，没有更改相关代码。华为那边没有再提过这个事儿。谢谢大佬
