### ISSUE TITLE
当屏幕中有其他容器时，listView无法做到自适屏高度

### ISSUE THREAD

**Issue by WallaceYou** [AbnerMing888/HarmonyOsRefresh#21]
我在使用时遇到个问题，如下代码：

@Entry
@Component
export struct TestPage {
  @State controller: RefreshController = new RefreshController() //刷新控制器
  @State array: Array<number> = []
  @State listHeight: number = 0

  aboutToAppear() {
    for (let i = 1; i <= 50; i++) {
      this.array.push(i)
    }
  }

  @Builder
  itemLayout(item: object, index: number){
    Text("测试数据" + item)
      .width("95%")
      .height(50)
      .margin(10)
      .textAlign(TextAlign.Center)
      .border({ width: 1, color: Color.Pink })
  }

  build() {
    Column() {
      Text('我是title')
        .fontSize(50)
        .textAlign(TextAlign.Center)
        .fontWeight(FontWeight.Bold)
        .height(60)
        .backgroundColor(Color.Blue)
        .width('100%')
      ListView({
        items: this.array, //数据源 数组
        itemLayout: (item:object, index:number) => this.itemLayout(item, index),
        controller: this.controller, //控制器，负责关闭下拉和上拉
        isLazyData: false,
        onRefresh: () => {
          //下拉刷新
          setTimeout(() => {
            this.controller.finishRefresh();
          }, 1000)
        },
        onLoadMore: () => {
          //上拉加载
          setTimeout(() => {
            this.controller.finishLoadMore();
          }, 1000)
        }
      })
    }
  }
}

此时，往下滑发现第50个默认在底部屏幕外，即listView高度超过了当前屏幕，测试发现超出部分正好是Title的高度60，如下图：

![Screenshot_2024-05-21T154859](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/15206765/50c32392-ab3f-4424-bcc8-390f791b8726)

于是给Listview添加自适应：

ListView({
      }).layoutWeight(1)
发现，确实可以显示完全了，但是出现了新的bug，顶部刷新文字显示到最上层了，如下图：

![Screenshot_2024-05-21T154934](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/15206765/1a18c76c-cb0c-4240-9a30-2b46386e68a5)

然后发现设置listView的attr属性的高度可以，但是在我目前实际项目中，上面还有很多其他容器，只能提前用屏幕高度减去所有容器高度，提前计算好listView的高度，然后赋值给attr属性吗，是否还有其他优化方案

**Comment by AbnerMing888** [comment]
你是说，当列表顶部有组件时，ListView底部的内容展示不全是吧？

**Comment by AbnerMing888** [comment]
高度自适应，已列入排期。

**Comment by WallaceYou** [comment]
> 你是说，当列表顶部有组件时，ListView底部的内容展示不全是吧？

感谢回复，对的，您可以看一下最后一张图（或者代码试一下），如果不给ListView设置高度，他高度貌似默认是整个Column的高度，所以下方超出去了，而设置了高度或者layoutWeight(1)自适应，高度对了，但是上方的刷新头部却显示了出来

**Comment by WallaceYou** [comment]
抱歉打扰，请问最新版是否有解决这个问题？

**Comment by halzhang** [comment]
遇到同样的问题。目前的解决方案是根布局用 stack，titlebar 叠在上面，listview 设置 padding top

**Comment by WallaceYou** [comment]
升级最新版1.2.0，经测试，问题已修复
