### ISSUE TITLE
懒加载时RefreshDataSource删除数据没有完全删除，导致数据展示错乱

### ISSUE THREAD

**Issue by sisychen** [AbnerMing888/HarmonyOsRefresh#24]
let dataLength = this.dataSource.totalCount()
      // 删除数据源里面的数据
      if (dataLength > 0) {
        for (let i = 0; i < dataLength; i++) {
          this.dataSource.deleteData(i)
        }
      }
      console.info(`==totalCount:${this.dataSource.totalCount()}`)
如果使用this.dataSource.deleteAll 再this.dataSource.pushData 页面不会刷新

以上情况都是出现在需要下拉刷新的情况下 多次刷新会出现以上问题。

**Comment by AbnerMing888** [comment]
删除全部紧接着就执行添加，可以执行回调，在删除全部后在添加，就不会有问题。
this.dataSource.deleteAll(() => {
this.dataSource.pushDataArray([300, 301, 302])
})

**Comment by sisychen** [comment]
还有个问题，已存在底部加载更多控件，如何进行隐藏，目前发现使用this.refreshController.closeLoadMore=false不生效

**Comment by AbnerMing888** [comment]
两种方式，一种是不设置onLoadMore，或者设置enableLoadMore为false即可

**Comment by winnxiegang** [comment]
删除全部紧接着就执行添加，可以执行回调，在删除全部后在添加，就不会有问题。
this.dataSource.deleteAll(() => {
this.dataSource.pushDataArray([300, 301, 302])
}) 这样执行 我虚拟机运 发现会有空白现象
