### ISSUE TITLE
使用 headerRefreshLayout 时，回调中的status并未发生改变

### ISSUE THREAD

**Issue by waynedeng01** [AbnerMing888/HarmonyOsRefresh#25]
目标是根据status渲染不同的组件，目前status一直处于完成的状态，无法按需渲染。请问是否还缺少什么条件？
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/44942279/026f0a96-24dc-46de-a3ff-b6f4a4bd4c83)

**Comment by AbnerMing888** [comment]
这个状态，我用了很多种方式，回调不过来，不过我增加了一种新的获取方式，通过控制器RefreshController来获取，里面我定义了两个状态一个是下拉getRefreshLayoutStatus()一个是上拉getLoadMoreLayoutStatus()，在1.1.1之后的版本已经支持。

**Comment by waynedeng01** [comment]
感谢回复，不过升级至1.1.2之后，仍然无法通过
        footerLoadLayout: () => {
          this.CustomLoadMore(this.controller.getLoadMoreLayoutStatus())
        },
的方式传递状态，是否有比较好的方式呢？

**Comment by AbnerMing888** [comment]
你的controller使用@State修饰了吗

**Comment by waynedeng01** [comment]
有的，基础代码参考的是本仓库中的examples
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/44942279/68213188-2473-499c-9e1d-12bcb06e58f2)

**Comment by waynedeng01** [comment]
这是我在项目中的用法

import { ListView, LoadMoreLayoutStatus, RefreshController, RefreshDataSource } from '@abner/refresh';

@Component
export struct Recommend {
  @StorageProp('currentBreakpoint') currentBreakpoint: string = 'sm';
  @State commodityList: Commodity[] = [];
  @State titleIndex: number = 0;
  @State activityTitleIndex: number = 0;
  @State controller: RefreshController = new RefreshController() //刷新控制器
  @State array: Array<number> = []
  @State dataSource: RefreshDataSource = new RefreshDataSource() //数据懒加载操作对象，执行数据增删改查

  @Builder
  itemLayout(_: number, index: number): void {
    FeedsCard({ text: String(index) })
  }

  aboutToAppear() {
    for (let i = 0; i < 5; i++) {
      this.array.push(i)
    }
  }

  @Builder
  CustomSwiper() {
    Swiper() {
      ForEach(swiperImage, (item: Resource) => {
        Image(item)
          .width($r('app.float.image_background_width'))
          .height($r('app.float.image_background_height'))
          .backgroundColor(Color.White)
      }, (item: Resource) => JSON.stringify(item))
    }
    .displayCount('auto')
    .autoPlay(true)
    .itemSpace(StyleConstants.ITEM_SPACE)
    .width(StyleConstants.FULL_WIDTH)
    .indicator(false)
    .margin({ top: $r('app.float.vp_twenty'), bottom: $r('app.float.vp_twenty') })
  }

  @Builder
  CustomLoadMore(status: LoadMoreLayoutStatus) {
    if (status === LoadMoreLayoutStatus.Pulling) {
      Text('上拉加载更多')
    } else if (status === LoadMoreLayoutStatus.Release) {
      Text('松开立即加载更多')
    } else if (status === LoadMoreLayoutStatus.Loading) {
      Text('加载中')
    } else {
      Text('')
    }
  }

  build() {
    Column() {
      ListView({
        itemHeaderLayout: () => {
          this.CustomSwiper()
        },
        refreshHeaderAttribute: (attr) => {
          attr.hideTime = true
          attr.releaseText = '松开刷新'
          attr.iconDown = $r('app.media.zc_refresh_header')
        },
        footerLoadLayout: () => {
          this.CustomLoadMore(this.controller.getLoadMoreLayoutStatus())
        },
        items: this.array,
        itemLayout: (item: Object, index: number) => {
          this.itemLayout(item as number, index) //转成你需要的对象
        },
        controller: this.controller, //控制器，负责关闭下拉和上拉
        onLazyDataSource: (dataSource: RefreshDataSource) => {
          this.dataSource = dataSource
        },
        onRefresh: () => {
          this.controller.finishRefresh()
        },
        onLoadMore: () => {
          this.dataSource.pushDataArray(new Array(4).fill(0))
          this.controller.finishLoadMore()
        }
      })
    }
  }
}

**Comment by AbnerMing888** [comment]
你在最新版本再验证下

**Comment by waynedeng01** [comment]
感谢回复，新版本验证中，自定义组件已经可以正常使用，但是仍存在向下滑弹出上拉加载的框的问题

复现方法
滑动到底部，触发出弹框（默认的），这时在屏幕中上部分向下滑动也会弹出loadMore的组件，不符合常规操作逻辑

**Comment by waynedeng01** [comment]
并且这种情况下弹出的加载状态会导致可视元素的遮挡

**Comment by JanzenChen** [comment]
大佬，我感觉这里的做法有点问题。这个问题是内部状态改变了，但是没有引起渲染树重绘，所以就没有走footerLoadLayout，至始至终，footerLoadLayout只是开始的时候走了一次而已。
我觉得渲染的时候应该不管状态，只渲染一次，然后手势拖动的时候，回调一个状态，用户自己根据这个状态回调去修改自己的渲染。
