### ISSUE TITLE
不是数据源可以是任意的吗，为什么报这个错？

### ISSUE THREAD

**Issue by jemmy-tang** [AbnerMing888/HarmonyOsRefresh#27]
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/24632824/8b3338d3-b5be-4739-9841-f81504c69ea0)

**Comment by AbnerMing888** [comment]
代码粘贴出来

**Comment by jemmy-tang** [comment]
> 代码粘贴出来

![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/24632824/345d309e-f5ab-4933-875c-7d7e83bddbe2)

**Comment by AbnerMing888** [comment]
export class TestBean {
  params?: number

  constructor(params?:number) {
    this.params = params
  }
}

@Entry
@Component
struct ListViewPage {
  @State controller: RefreshController = new RefreshController() //刷新控制器
  @State array: TestBean[] = []

  aboutToAppear() {
    for (let i = 0; i < 20; i++) {
      this.array.push(new TestBean(i))
    }
  }

  /**
   * Author:AbnerMing
   * Describe:条目布局
   * @param item  数据对象
   * @param index  数据索引
   */
  @Builder
  itemLayout(bean: TestBean, index: number): void {
    Text("测试数据" + bean.params)
      .width("95%")
      .height(50)
      .margin(10)
      .textAlign(TextAlign.Center)
      .border({ width: 1, color: Color.Pink })
  }

  build() {
    Column() {
      ActionBar({ title: "普通的列表ListView" })
      ListView({
        items: this.array, //数据源 数组，可以任意类型，自定义对象[],number[],string[]……
        itemLayout: this.itemLayout //转成你需要的对象
      })
    }
  }
}

**Comment by AbnerMing888** [comment]
以上是一个Demo，你可以看下是否有问题，（由于github代码有转义，复制后可修改，比如@builder改为@Builder）

**Comment by jemmy-tang** [comment]
我编辑器和模拟器重启后，又ok了 !- - 老出现莫名其妙的问题

**Comment by jemmy-tang** [comment]
> export class TestBean { params?: number
> 
> constructor(params?:number) { this.params = params } }
> 
> @entry @component struct ListViewPage { @State controller: RefreshController = new RefreshController() //刷新控制器 @State array: TestBean[] = []
> 
> aboutToAppear() { for (let i = 0; i < 20; i++) { this.array.push(new TestBean(i)) } }
> 
> /**
> 
> * Author:AbnerMing
> * Describe:条目布局
> * @param item  数据对象
> * @param index  数据索引
>   */
>   @builder
>   itemLayout(bean: TestBean, index: number): void {
>   Text("测试数据" + bean.params)
>   .width("95%")
>   .height(50)
>   .margin(10)
>   .textAlign(TextAlign.Center)
>   .border({ width: 1, color: Color.Pink })
>   }
> 
> build() { Column() { ActionBar({ title: "普通的列表ListView" }) ListView({ items: this.array, //数据源 数组，可以任意类型，自定义对象[],number[],string[]…… itemLayout: this.itemLayout //转成你需要的对象 }) } } }

又出现这个问题了，我尝试了上面的代码，是没问题的。但是日常开发中不可能是这么简单的数据结构（接口下发会复杂很多），所以我想用一个类来接数据，麻烦看一下我想实现的数据结构，为什么会有问题，代码如下：
//这里数据示例
class TestBean {
  array: number[] = []
}

@Entry
@Component
export struct ListViewPage {
  @State controller: RefreshController = new RefreshController() //刷新控制器
  @State testBean: TestBean = new TestBean();

  aboutToAppear() {
    for (let i = 0; i < 20; i++) {
      this.testBean.array.push(i)
    }
  }

  @Builder
  itemLayout(bean: object, index: number) {
    Text("测试数据" + bean)
      .width("95%")
      .height(50)
      .margin(10)
      .textAlign(TextAlign.Center)
      .border({ width: 1, color: Color.Pink })
  }

  build() {
    Column() {
      ListView({
        items: this.testBean.array,
        itemLayout: this.itemLayout
      })
    }
  }
}
