### ISSUE TITLE
您好我想拿到 ListView 的滑动偏移量应该在哪里获取

### ISSUE THREAD

**Issue by mm2m123** [AbnerMing888/HarmonyOsRefresh#28]

**Comment by AbnerMing888** [comment]
Scroller可以拿到的

**Comment by gaoxuge521** [comment]
Scroller怎么拿啊？没找到相关属性啊

**Comment by waynedeng01** [comment]
> > Scroller怎么拿啊？没找到相关属性啊
> 
> > Scroller怎么拿啊？没找到相关属性啊
> 
> onScrollFrameBegin回调里面好像可以。 原生的List里面，可以通过`this.scroller.currentOffset().yOffset`获取

你好，能提供一个小的demo吗？我获取的值一直为0

**Comment by mm2m123** [comment]
我这边是先
scroller: Scroller = new Scroller()
然后
Scroll(this.scroller) {
        ListView({
          scroller: this.scroller,
        })
      }
      .height('100%')
      .width('100%')
      .onWillScroll(() => {
        this.yOffset = this.scroller.currentOffset().yOffset
      })
      
      差不多这样用的

**Comment by waynedeng01** [comment]
> 我这边是先 scroller: Scroller = new Scroller() 然后 Scroll(this.scroller) { ListView({ scroller: this.scroller, }) } .height('100%') .width('100%') .onWillScroll(() => { this.yOffset = this.scroller.currentOffset().yOffset })
> 
> ```
>   差不多这样用的
> ```

好的，感谢，方便问下你使用的版本吗？我尝试后仍然是0，想看看是否为版本的问题

**Comment by waynedeng01** [comment]
这边尝试将结构做了最简化，仍然是无法正常拿到偏移量，但是页面表现，以及onwillScroll都是正常触发的
![image](https://github.com/user-attachments/assets/7a0e94a5-88e9-426f-841c-bb9dec57d174)
