### ISSUE TITLE
关于懒加载的设计问题

### ISSUE THREAD

**Issue by TokenYc** [AbnerMing888/HarmonyOsRefresh#30]
作者你好，关于懒加载下的使用，我有些疑问：
1、为何要传入items、dataSource两个数据源？dataSource内部本身就可以维护数据List吧，按理说，初始化不需要再额外传入Items？
2、DataSource是否考虑下支持设置数据的泛型，个人感觉这样使用会方便些。

**Comment by jemmy-tang** [comment]
> 作者你好，关于懒加载下的使用，我有些疑问： 1、为何要传入items、dataSource两个数据源？dataSource内部本身就可以维护数据List吧，按理说，初始化不需要再额外传入Items？ 2、DataSource是否考虑下支持设置数据的泛型，个人感觉这样使用会方便些。

+1
而且首次初始化数据的时候必须把数据塞到items内，后续的上拉加载/下拉刷新，又要用DataSource来操作

**Comment by AbnerMing888** [comment]
目前针对这块做了优化，可以只传DataSource

**Comment by AbnerMing888** [comment]
DataSource目前用的是Object，支持任意类型，UI组件回调回来的也是Object，在渲染的时候转成你的对象即可，要使用泛型，需要解决，UI回传也是你的类型，目前没有找到好的解决方式

**Comment by jemmy-tang** [comment]
> > 目前针对这块做了优化，可以只传DataSource
> 
> 感谢，试了下，确实是可以的。

用懒加载了吗？能否贴下代码借鉴一下

**Comment by TokenYc** [comment]
> > > 目前针对这块做了优化，可以只传DataSource
> > 
> > 
> > 感谢，试了下，确实是可以的。
> 
> 用懒加载了吗？能否贴下代码借鉴一下

用了懒加载，组件初始化时，不用传入`items`，统一使用`dataSource`管理。添加数据使用`dataSource`的`pushDataArray`方法就可以了。
