### ISSUE TITLE
懒加载模式下，下拉刷新更新数据问题

### ISSUE THREAD

**Issue by TokenYc** [AbnerMing888/HarmonyOsRefresh#31]
有一个常见的场景是下拉刷新，请求接口，然后清除列表数据，重新添加数据。
如果按照这种写法，下拉刷新时，会闪一下，由于源码不开源，个人猜测是deleteAll中调用了数据更新的方法导致。
```
this.dataSourceRefresh.deleteAll(() => {
  this.dataSourceRefresh.pushDataArray(response.feed)
})
```
于是，换了一种写法，只清除数据，不调用更新，这样是不会闪的。作者能否考虑直接在dataSource中添加一个这样的方法？
```
let allData = this.dataSourceRefresh.getDataAll()
allData.splice(0, allData.length)
this.dataSourceRefresh.pushDataArray(response.feed)
```

**Comment by winnxiegang** [comment]
我也是 this.dataSourceRefresh.deleteAll(() => {
  this.dataSourceRefresh.pushDataArray(response.feed)
}) 操作 会闪一下

**Comment by AbnerMing888** [comment]
好的，我验证一下

**Comment by AbnerMing888** [comment]
初步猜测是因为调用了DataSource的notifyDataAdd，造成的闪烁，你全部清空后既无数据了，添加后又渲染数据了

**Comment by waynedeng01** [comment]
另外调用 this.controller.finishLoadMore(true) 之后，状态似乎无法复原

**Comment by jemmy-tang** [comment]
> 另外调用 this.controller.finishLoadMore(true) 之后，状态似乎无法复原

我试了一下，可以，下拉刷新后重新调一下this.controller.finishLoadMore(false)
