### ISSUE TITLE
懒加载时RefreshDataSource 会出现重复显示

### ISSUE THREAD

**Issue by winnxiegang** [AbnerMing888/HarmonyOsRefresh#33]
HomeViewModel.getBrandList(this.currentPage, ((result: BrandItemBean[]) => {
      if (this.currentPage === 1) {
        this.brandListData = result
        //添加额外的数据 并置顶展示
        this.listLitterDetails.forEach((value) => {
          this.brandListData.unshift(new BrandItemBean(
            null, value))
        })
      } else {
        this.brandListData.push(...result)
      }
      this.refreshController.finishRefresh()
      this.refreshController.finishLoadMore(this.brandListData.length < 10)

      this.dataSource.pushDataArray(this.brandListData)
    }));

  / 额外的数据  会每次请求都展示一次 就是每一次请求 都重复添加进去 展示了

**Comment by AbnerMing888** [comment]
数据的增删改查都是自己来操作的，你说的重复，是自己添加重复了，还是？

**Comment by halzhang** [comment]
组件 有 bug 吧，多调用              this.dataSource.reloadData() 试试

**Comment by ant074** [comment]
确实就是组件bug，也不知道为什么会关闭issue。1.3.5还是有，数据更新了，UI刷新就会重复显示

**Comment by ant074** [comment]
现在能使用的一种方式是：
在刷新数据之前，先执行dataSource.deleteAll，在回调中再去执行刷新接口，返回中执行deleteAllAfterPushArray或其他push操作，才可以真正的有效刷新
