### ISSUE TITLE
[bug] 向下滑弹出上拉框（loadmore）

### ISSUE THREAD

**Issue by waynedeng01** [AbnerMing888/HarmonyOsRefresh#34]
版本 V1.1.4

复现方法

滑动到底部，触发出弹框（默认的），这时在屏幕中上部分向下滑动也会弹出loadMore的组件，不符合常规操作逻辑

**Comment by AbnerMing888** [comment]
任意一个弹框吗？就是触发一个普通的弹框是吧，我明天测试一下

**Comment by waynedeng01** [comment]
可能表述有点不清晰，就是触发一个loadMore的框（页面已经在底部），这个时候在屏幕的中上部分向下滑动，会让loadMore的框再次弹出（与常规逻辑不符合，应该是在底部向上滑动才会触发出loadMore才对）

**Comment by waynedeng01** [comment]
今早尝试了新版本 V1.1.5，同样操作路径依旧可以复现

**Comment by waynedeng01** [comment]
最新版本已经修复，感谢
