### ISSUE TITLE
自定义下拉刷新头和加载尾的回掉种，返回的状态永远都是3，状态不会变更

### ISSUE THREAD

**Issue by jemmy-tang** [AbnerMing888/HarmonyOsRefresh#35]
如题
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/24632824/1643b902-4de9-49ad-9155-36403d2bfcf5)

**Comment by AbnerMing888** [comment]
这里的状态回调不过来，请使用另一种获取方式，使用RefreshController里的getRefreshLayoutStatus 和getLoadMoreLayoutStatus

**Comment by jemmy-tang** [comment]
这样子的话headerRefreshLayout，footerLoadLayout这两个意义不大了，相信很多人应该都会需要自定义这两个UI吧。
而且getRefreshLayoutStatus 和getLoadMoreLayoutStatus这两个方法是不是还要放在scroller里面时时获取，会不会带来性能问题。

**Comment by AbnerMing888** [comment]
文档中有写这两个属性，它类似于回调，有状态改变就会触发。

**Comment by jemmy-tang** [comment]
好的，我试试

**Comment by jemmy-tang** [comment]
OK了，完美实现，目前还有个问题是下拉完成后直接回弹了，能否支持允许自定义延迟一段时间后进行回弹效果。

**Comment by AbnerMing888** [comment]
直接回弹，是因为，你没有做任何操作，直接关闭了刷新吧，如果你是做了逻辑处理，比如请求了网络或者其他，肯定有耗时操作的，等数据请求回来后再关闭，就不会直接回弹了。如果你想要延迟，也可以在业务层自定义延迟后操作。

**Comment by jemmy-tang** [comment]
之前自己封装其他端的时候确实是有一个中间态，当然希望refresh组件里自带这样的功能更好，这样更灵活可控，方便不同的需求
