### ISSUE TITLE
是否有想法将loading状态抛出（能够设置组件loading）

### ISSUE THREAD

**Issue by waynedeng01** [AbnerMing888/HarmonyOsRefresh#36]
场景：

为了组件高效复用，很多时候我们将大多数公共逻辑封装，并从父组件提供数据源，会在父组件调用请求，并给到loading状态；然而当前refresh组件中，并没有合适的地方去设置loading，导致不知道在什么时机去关闭loading状态

          onRefresh: () => {
            if (this.handleRefresh) {
              this.handleRefresh() // 调用父组件请求
            }
            if (!this.FeedsContentLoading) {
              // 优化屏幕闪烁，直接使用deleteAll()会导致屏幕闪烁
              const allData = this.dataSource.getDataAll()
              allData.splice(0, allData.length)
              this.dataSource.pushDataArray(this.FeedsContentData.contentList)
              this.controller.finishRefresh()
            }
          },
          onLoadMore: () => {
            if (this.handleLoadMore) {
              this.handleLoadMore()
            }
            if (!this.FeedsContentLoading) {
              if (this.FeedsContentData?.contentList?.length) {
                this.dataSource.pushDataArray(this.FeedsContentData.contentList)
                this.controller.finishLoadMore()
              } else {
                this.dataSource.pushData({ isEnd: true })
                this.controller.finishLoadMore(true)
              }
            }
          }

**Comment by AbnerMing888** [comment]
你的loading是加载到页面中间的是吗
