### ISSUE TITLE
刷新的时候 不可滑动问题

### ISSUE THREAD

**Issue by lingjianglin** [AbnerMing888/HarmonyOsRefresh#37]
好像 下拉的时候 ，正在刷新刷新中列表不能响应手势滑动了，但是上拉加载更多的时候 ，列表可以滑动，怎么设置上拉的时候 也不能滑动

**Comment by lingjianglin** [comment]
源码 没有开放么，怎么可以看到源代码实现

**Comment by AbnerMing888** [comment]
收到，下个版本我加上了

**Comment by 594238813** [comment]
新版 好像还是不行， 下拉刷新，  上拉加载更多 还是不能滑动。
并且   setTimeout(() => {
            //模拟耗时
            this.controller.finishLoadMore()
          }, 7000)     
如果时间长 ，滑动列表。 会报错，不会闪退。 应该是anr了吧？
