### ISSUE TITLE
使用GridVIew吸顶时，没到最顶部就开始刷新了

### ISSUE THREAD

**Issue by ehuiz** [AbnerMing888/HarmonyOsRefresh#38]
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/40593897/466b66bf-4870-4d56-b9d5-5797b9a6d98d)
代码如下 ：
GridView({
      items: this.arr,
      itemLayout: this.itemLayout,
      controller: this.controller,
      onRefresh: () => {
        //下拉刷新
        //模拟耗时
        setTimeout(() => {
          this.controller.finishRefresh()
        }, 1000)
      },
      onLoadMore: () => {
        // 上拉加载
        //模拟耗时
        setTimeout(() => {
          this.controller.finishLoadMore()
        }, 1000)
      },
      nestedScroll:{
        scrollForward: NestedScrollMode.PARENT_FIRST,
        scrollBackward: NestedScrollMode.SELF_FIRST
      }
     /* listAttribute: (attr) => {
        attr.nestedScroll = {
          scrollForward: NestedScrollMode.PARENT_FIRST,
          scrollBackward: NestedScrollMode.SELF_FIRST
        }
      }*/
    })

**Comment by AbnerMing888** [comment]
你看我的Demo中的代码，有案例

**Comment by AbnerMing888** [comment]
你看我的Demo中的代码，有案例

**Comment by ehuiz** [comment]
> 你看我的Demo中的代码，有案例

是StaggeredGridView吗 ，没看到有单独的GridView吸顶示例
