### ISSUE TITLE
使用瀑布流吸顶时，网络加载更新list数据时，不刷新数据

### ISSUE THREAD

**Issue by ehuiz** [AbnerMing888/HarmonyOsRefresh#39]
如果将瀑布流换成GridVIew，没有此问题，
是不是因为 瀑布流组件  items使用了@State
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/40593897/ff4f4969-ed3c-4108-8f1b-d839665b9495)

**Comment by AbnerMing888** [comment]
是这个问题，请在下一个版本进行验证
