### ISSUE TITLE
懒加载 deleteAll后立即pushDataArray，数据显示错误

### ISSUE THREAD

**Issue by ehuiz** [AbnerMing888/HarmonyOsRefresh#40]
正常显示 应该是 从10开始
![1717472582926](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/40593897/e60c459a-4288-4ab7-beb7-7432b2a71a6f)
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/40593897/2f474aad-477a-400d-bc0b-1584ef18e44e)
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/40593897/673ca1e7-3e05-4742-b88a-a9f1f09d5043)

**Comment by AbnerMing888** [comment]
之前的问题回答过，删除全部那有回调，可以在回调后在执行添加即可
