### ISSUE TITLE
ListView侧滑按钮不关闭

### ISSUE THREAD

**Issue by howlshit** [AbnerMing888/HarmonyOsRefresh#41]
## 流程描述
1、ListView侧滑按钮中使用dataController删除数据后
2、接着下拉刷新，发现被删的数据项突然出现，且是被删前的侧滑状态

#### 删除前
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/42687631/94d42923-d719-4ff2-abf2-5d7f28128b3c)

#### 删除后
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/42687631/dd467811-0efe-4adb-a62e-cd2497be4809)

#### 下拉刷新时：
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/42687631/854c36d8-2908-4d3d-9d82-e3ba42bcc00c)

**Comment by AbnerMing888** [comment]
好的，可以在下一个版本验证

**Comment by AbnerMing888** [comment]
好的，可以在下一个版本验证

**Comment by howlshit** [comment]
> 好的，可以在下一个版本验证

问题修复了

**Comment by howlshit** [comment]
## 问题描述
删除数据时，侧滑按钮已关闭，但下拉刷新被删数据又出现


## 过程图示

#### 删除前
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/42687631/b7d50436-bb0f-48a0-b4f4-0af99ea514b4)


#### 删除后
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/42687631/37324651-67bc-4708-8da5-6de126831eb1)


#### 下拉刷新时
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/42687631/ffdcc572-2f08-4f40-8d7b-53c436632930)


#### 下拉刷新完
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/42687631/a9e8e639-a71a-44f9-9f42-fc5a47d553a7)
