### ISSUE TITLE
配合Tab使用 示例貌似有点问题

### ISSUE THREAD

**Issue by lcc1121** [AbnerMing888/HarmonyOsRefresh#42]
一个tabContent都是一个独立的页面，滑动位置状态，实际都是独立
这时候用同一个array数据源会出现问题

import { ToolbarStatusLayout } from '../../component/toolbarStatus/Index'
import Common from "../../../utils/Common"
import { ListView, RefreshController } from '@abner/refresh'
import { TabLayout } from '@abner/tab'
import { InfoItem } from "../home/component/Info"

@Component
struct ItemPage {
  @State array: Array<number> = [1, 2, 3, 4, 5, 6]
  @State listRefreshController: RefreshController = new RefreshController()

  @Builder
  itemLayout(_: number, index: number): void {
    Text("测试数据" + index)
      .width("95%")
      .height(50)
      .margin(10)
      .textAlign(TextAlign.Center)
      .border({ width: 1, color: Color.Pink })
  }

  build() {
    ListView({
      items: this.array, //数据源 数组，可以任意类型，自定义对象[],number[],string[]……
      itemLayout: (item: Object, index: number) => {
        this.itemLayout(item as number, index) //转成你需要的对象
      },
      controller: this.listRefreshController, //控制器，负责关闭下拉和上拉
      onRefresh: () => {
        console.log("下拉刷新了");
        //下拉刷新
        this.listRefreshController.finishRefresh()
      },
      onLoadMore: () => {
        console.log("上拉加载更多了")
        this.array.push(this.array.length)
        this.listRefreshController.finishLoadMore()
      }
    })
  }
}

@Entry
@Component
export struct Info {
  @State tabList: Array<string> = ["1", "2", "3", "4"]
  @State listRefreshController: Array<RefreshController> = []
  handleBack = () => {
    Common.back()
  }

  @Builder
  itemPage(_this: Info, index: number, item: string) {
    ItemPage()
  }

  @Builder
  itemLayout(_: number, index: number): void {
    Text("测试数据" + index)
      .width("95%")
      .height(50)
      .margin(10)
      .textAlign(TextAlign.Center)
      .border({ width: 1, color: Color.Pink })
  }

  build() {
    Column() {
      ToolbarStatusLayout({
        toolbarProps: {
          title: "资讯",
          showLeftText: true,
          leftClick: this.handleBack
        }
      }) {
        Column() {
          TabLayout({
            //不能滑动
            tabScrollable: false,
            tabBar: this.tabList,
            //均分
            barMode: BarMode.Fixed,
            itemPage: (index: number, item: string) => {
              this.itemPage(this, index, item)
            },
            //设置属性
            tabAttribute: (tab) => {
              tab.tabSelectedColor = Color.Red
              tab.tabDividerColor = Color.Red
            },
            //点击改变
            onTabBarClick: (position) => {
              console.log("点击改变:" + position)
            }
          })
        }.width("100%")
        .height("85%")
      }
    }
  }
}
可能这样抽出来是不是会是独立的

**Comment by AbnerMing888** [comment]
demo中只是简单得案例，实际应以业务需求为主，每个tab下对应得数据是不一样的，有时UI也不一样，按照实际开发即可。
