### ISSUE TITLE
RefreshLayoutStatus状态有的少

### ISSUE THREAD

**Issue by gaoxuge521** [AbnerMing888/HarmonyOsRefresh#44]
自定义刷新头，我想在下拉时开启动画，关闭时结束动画，现在有个问题，我下拉一点点，动画开启，然后松开，动画关不了了。
Finish状态是刷新头拉到最下面才变。需要一个状态知道刷新头已经关闭

**Comment by AbnerMing888** [comment]
所有的状态都在RefreshController里面
 closeRefresh: boolean = false; //刷新是否关闭 true为关闭
  closeLoadMore: boolean = false; //加载是否关闭 true为关闭
