### ISSUE TITLE
如果顶部的内容所占高度超过一定的，比如160vp，再使用下拉刷新自定义内容，会出现一点问题

### ISSUE THREAD

**Issue by fantacy-Xu** [AbnerMing888/HarmonyOsRefresh#51]
如果顶部的内容所占高度超过一定的，比如160vp，再使用下拉刷新自定义内容，会出现顶部的数据会有一点点被遮挡。只有顶部内容少的时候才不会有遮挡，请问这个问题可以考虑优化一下吗？虽然说在外部再加些高度把遮挡区的内容挤出去也能显示，但终归不太友好。

**Comment by waynedeng01** [comment]
这边也有同样的问题，使用自定义刷新头的时候，超出一定的高度，就会造成遮挡
