### ISSUE TITLE
下拉刷新UI层级在导航栏更高，会露出来 ，怎么解决？

### ISSUE THREAD

**Issue by jemmy-tang** [AbnerMing888/HarmonyOsRefresh#59]
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/24632824/441757d3-0b47-48cf-9c15-06d27832c909)

**Comment by AbnerMing888** [comment]
使用最新的版本是否还存在问题

**Comment by jemmy-tang** [comment]
目前使用的1.1.7版本
