### ISSUE TITLE
延迟添加数据后，懒加载模式下，显示不了数据

### ISSUE THREAD

**Issue by saiHelloWorld** [AbnerMing888/HarmonyOsRefresh#6]
延迟添加数据后，默认懒加载模式下，数据添加成功了，但是显示不了数据，改成非懒加载模式就能正常显示数据，如下代码，在ListViewRefreshPage页面的aboutToAppear里加了一个setTimeout，页面一片空白。网络请求的数据都是延迟加载

struct ListViewRefreshPage {
  @State controller: RefreshController = new RefreshController() //刷新控制器
  @State array: Array<number> = []

  aboutToAppear() {
    setTimeout(() => {
      for (let i = 0; i < 20; i++) {
        let result = this.array.push(i)
        console.log('push result: ' + result)
      }
    }, 1000);
  }

**Comment by AbnerMing888** [comment]
懒加载数据，使用文档我更新了，这个大意了没有更新到文档，数据懒加载必须使用dataSource进行数据的增删改查

@State controller: RefreshController = new RefreshController() //刷新控制器，声明全局变量
@State dataSource: RefreshDataSource = new RefreshDataSource()//数据懒加载操作对象，执行数据增删改查
        
ListView({
  items: this.array, //数据源 数组,任意类型
  itemLayout: (item, index) => this.itemLayout(item, index), //条目布局
  controller: this.controller, //控制器，负责关闭下拉和上拉
  onLazyDataSource: (dataSource: RefreshDataSource) => {
    this.dataSource = dataSource
  },
  onRefresh: () => {
    //下拉刷新
    //数据懒加载使用：1、数组数据添加，this.dataSource.pushDataArray()，2、单个数据添加，this.dataSource.pushData()
    this.controller.finishRefresh() //关闭下拉刷新，在数据请求回后进行关闭
  },
  onLoadMore: () => {
    //上拉加载
    //数据懒加载使用：1、数组数据添加，this.dataSource.pushDataArray()，2、单个数据添加，this.dataSource.pushData()
    this.controller.finishLoadMore() //关闭上拉加载,在数据请求回后进行关闭
  }
})
