### ISSUE TITLE
ListView自定义刷头部，status始终为3

### ISSUE THREAD

**Issue by XiongZP** [AbnerMing888/HarmonyOsRefresh#60]
使用ListView自定义刷头部，我想实现下拉时，不同状态展示不同的文字

可以现在下拉时所有的状态都是3，该如何处理呢？

![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/10695258/b3e89dd9-4c2f-49bb-8852-20a81677e637)

**Comment by AbnerMing888** [comment]
使用控制器中的状态获取即可：this.controller.getRefreshLayoutStatus()
