### ISSUE TITLE
是否支持通过API触发下拉下

### ISSUE THREAD

**Issue by lzjtugjc** [AbnerMing888/HarmonyOsRefresh#61]
是否可以通过一些API触发下拉刷新或者关闭下拉刷新：比如startRefresh、stopRefresh；通过API触发之后，依旧支持通过手势操作，比如上滑关闭下拉刷新等

**Comment by AbnerMing888** [comment]
有属性支持的，你可以通过属性控制enableRefresh，enableLoadMore，动态传递即可

**Comment by geeklx** [comment]
大佬上面的意思应该我理解是进来自动刷新

**Comment by AbnerMing888** [comment]
自动刷新也是支持的，使用控制器中autoRefresh即可
