### ISSUE TITLE
带有头的demo有问题

### ISSUE THREAD

**Issue by geeklx** [AbnerMing888/HarmonyOsRefresh#62]
滑到最后 看不到加载更多了
怎么能一直显示footer

**Comment by AbnerMing888** [comment]
能告诉我你使用的版本吗

**Comment by geeklx** [comment]
跟版本无关，大佬 就是很多人提的这个问题，

https://github.com/AbnerMing888/HarmonyOsRefresh/issues/48

现在市面上大部分的效果都是要显示没有更多数据了的footer的，而不是现在的需要回弹过加载完成再显示footer，并且一松手又回弹隐藏了

**Comment by JasonYinH** [comment]
+1，目前公司就是没有数据了，直接在下面显示暂无数据
