### ISSUE TITLE
你好，想拿到this.controller.currentOffset().yOffset;应该怎么拿

### ISSUE THREAD

**Issue by gaoxuge521** [AbnerMing888/HarmonyOsRefresh#64]
系统list有个滑动量，this.controller.currentOffset().yOffset;这个怎么拿？

**Comment by AbnerMing888** [comment]
提供了scroller?: Scroller属性，你可以传递，或者，你可以通过onScroll或其他属性获取

**Comment by waynedeng01** [comment]
> 提供了scroller?: Scroller属性，你可以传递，或者，你可以通过onScroll或其他属性获取

尝试了这么去做，onscroll也确实正常触发了，但是获取到的值一直是0
