### ISSUE TITLE
controller.autoRefresh(true) 引起滑动问题

### ISSUE THREAD

**Issue by Gaara33** [AbnerMing888/HarmonyOsRefresh#66]
控件可见时调用controller.autoRefresh(true)触发自动刷新，刷新拿到数据结束后，listview无法下拉，无法手动触发下拉刷新，只能上拉一下（很小距离即可），然后才能下拉滑动至下拉刷新，后续刷新数据后不再复现此问题，只有收下下拉刷新后。使用版本为1.1.8

**Comment by Gaara33** [comment]
升级到1.1.9版本  此问题依然存在，在控件aboutToAppear方法中请求数据，数据填充后无法下拉，不调用autoRefresh自动刷新也是这个现象

**Comment by AbnerMing888** [comment]
问题已关注，确实存在，非常抱歉，1.1.8版本重构导致，请在1.2.0版本验证。

**Comment by Gaara33** [comment]
版本1.2.0此问题已经不复现，👍🏻

**Comment by Gaara33** [comment]
1.2.0版本已不复现此问题，👍🏻
还有个小问题，首次加载数据（请求数据失败），无数据显示了空图（占满显示区域），空图展示后，在空图区域无法下拉刷新，再次调用自动刷新后，无法下拉刷新现象变为偶现，希望后续版本能优化一下。

**Comment by AbnerMing888** [comment]
感谢提出宝贵的问题，请在1.2.1版本验证。

**Comment by Gaara33** [comment]
1.2.1版本没有复现 👍🏻👍🏻
