### ISSUE TITLE
ListView设置header之后，滑动的偏移量问题

### ISSUE THREAD

**Issue by quanquan111** [AbnerMing888/HarmonyOsRefresh#67]
1.1.8 在设置header之后，滑动偏移量在header滑完之后才开始有回调，有其他方法可以监听吗？

附上监听截图

<img width="566" alt="image" src="https://github.com/AbnerMing888/HarmonyOsRefresh/assets/26267467/6deadb77-2992-4cdb-81c2-e8291dc8a3a6">

经测试只要没有下拉出刷新头时， 往上滑动回调正常， 往下拉回调为0，拉出刷新头之后在header没有滑出去都是0，出去之后正常回调。

**Comment by quanquan111** [comment]
经测试只要没有下拉出刷新头时， 往上滑动回调正常， 往下拉回调为0，拉出刷新头之后在header没有滑出去都是0，出去之后正常回调。

**Comment by AbnerMing888** [comment]
你是想拿到onScroll方法是吧

**Comment by quanquan111** [comment]
> 你是想拿到onScroll方法是吧

是的， 另外在1.1.8版本上面还发现两个问题
1、ListView设置header之后下拉速度过快有时候会出现header不动， item往上滚动
2、ListView设置header如果item的dataSources为空， header也不会显示出来
