### ISSUE TITLE
RefreshLayout加载任意组件中出现Grid会加载不出来数据

### ISSUE THREAD

**Issue by projectxxl** [AbnerMing888/HarmonyOsRefresh#68]
1.1.7版本下，使用RefreshLayout加载任意组件，在itemLayout中如果出现Grid，Grid中的数据无法加载出来

**Comment by AbnerMing888** [comment]
大概率是你的this指向不对，Builder中，传入数据时，尽量把this传进来，用于获取定义的数据

**Comment by projectxxl** [comment]
我的itemLayout是这样写的，确实加载不出来
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/50988096/fc3c3b6a-a422-467e-848f-da33d33b885f)
