### ISSUE TITLE
通过 this.dataSource.deleteData(position) 挨个删除 删除到最后一条的时候，无法移除

### ISSUE THREAD

**Issue by artillerymans** [AbnerMing888/HarmonyOsRefresh#69]
使用的 this.dataSource.deleteData(position)删除

**Comment by AbnerMing888** [comment]
你确定吗？我测试了，没问题的

**Comment by artillerymans** [comment]
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/16060581/efdd1fb9-b111-4b3c-ab2b-d7550cd7f493)
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/16060581/631bb498-81ed-413a-9c07-b0aadaf5f8a9)
这个列表 有三条数据  我点击开红包 就会删除掉一条 依次从上往下删除  或是根据 itemLayout中的index去拿到下标删除的 从删除第二个开始 其实下标就不对了  因为我始终点击的是第一个也就是 index == 0 这个

**Comment by artillerymans** [comment]
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/16060581/88dcd975-d60b-4cff-ae22-86ac5457a035)
给到里面的index在渲染完成后就不变了吗  我在 itemView中定义了回调事件 点击后就把index携带出去 当成删除的下标，亦或者删除后需要重新刷新吗

**Comment by artillerymans** [comment]
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/16060581/245e68ed-496f-4649-b73a-9a1d6e527f25)
这样删除就没有问题 如果不调用notifyDataReload 删除第二个开始就会有问题

**Comment by AbnerMing888** [comment]
是的，官方为防止索引异常，需要重置索引的，你需要调用notifyDataReload或者reloadData都行
