### ISSUE TITLE
【需求】支持文本自定义

### ISSUE THREAD

**Issue by chenqinggang001** [AbnerMing888/HarmonyOsRefresh#7]
支持文本自定义
{
  "string": [
    {
      "name": "page_show",
      "value": "page from npm package"
    },
    {
      "name": "header_pulling",
      "value": "下拉可以刷新"
    },
    {
      "name": "header_refreshing",
      "value": "正在刷新…"
    },
    {
      "name": "header_loading",
      "value": "等待底部加载完成…"
    },
    {
      "name": "header_release",
      "value": "释放立即刷新"
    },
    {
      "name": "header_finish",
      "value": "刷新完成"
    },
    {
      "name": "header_failed",
      "value": "刷新失败"
    },
    {
      "name": "header_update",
      "value": "上次更新 M-d HH:mm"
    },
    {
      "name": "footer_pulling",
      "value": "上拉加载更多"
    },
    {
      "name": "footer_release",
      "value": "释放立即加载"
    },
    {
      "name": "footer_loading",
      "value": "正在加载…"
    },
    {
      "name": "footer_refreshing",
      "value": "等待头部刷新完成…"
    },
    {
      "name": "footer_finish",
      "value": "加载完成"
    },
    {
      "name": "footer_failed",
      "value": "加载失败"
    },
    {
      "name": "footer_nothing",
      "value": "没有更多数据了"
    }
  ]
}

**Comment by chenqinggang001** [comment]
如果有源码我可以提交pr

**Comment by AbnerMing888** [comment]
好的，我抽时间加下，目前还有很多东西优化，还不成熟，等公司项目测试的无问题，源码就出来
