### ISSUE TITLE
RefreshLayout配合嵌套Scroll滑动冲突

### ISSUE THREAD

**Issue by zsp19931222** [AbnerMing888/HarmonyOsRefresh#71]
我在滑动页面的时候，还没到顶部的时候下拉刷新的组件也显示出来了

**Comment by DancingDuck** [comment]
+1 快速滑动很容易出现

**Comment by DancingDuck** [comment]
参考作者SystemListViewPage 自己控制top bottom 已解决

**Comment by loveliveis** [comment]
贴下代码看下

**Comment by DancingDuck** [comment]
冲突参考作者示例SystemListViewPage
如：
![Uploading `WA2YJ]6M8WAUQ)B{DB)]D2.png…]()

**Comment by DancingDuck** [comment]
冲突参考作者示例SystemListViewPage
如：
![`WA2YJ 6M8WAUQ)B{DB) D2](https://github.com/user-attachments/assets/ff0f2968-e02b-4f1f-831e-be87ad5b2b51)

**Comment by loveliveis** [comment]
注意看判断， 当嵌套的事List的时候在手势上划过程中， Y坐标必为负值， 此时没有到顶部也没有到底部的时候，也是会触发刷新

**Comment by loveliveis** [comment]
从上往下滑的时候，Y坐标别为负值，还是会走center的代码，会触发下拉刷新。（上面手势上划，表达错误）

**Comment by loveliveis** [comment]
<img width="718" alt="image" src="https://github.com/user-attachments/assets/c677f17b-c782-4e05-a29a-7b5e81733bf2">
忘记了这两个属性，现在可以了

**Comment by DancingDuck** [comment]
1.3.3这个问题复现了
