### ISSUE TITLE
DataController.deleteData()删除数据后，下拉时出现被删数据

### ISSUE THREAD

**Issue by howlshit** [AbnerMing888/HarmonyOsRefresh#73]

**Comment by AbnerMing888** [comment]
??你是如何操作的

**Comment by howlshit** [comment]
删除前
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/42687631/94d0838b-9916-4e69-b524-5e3dc0f8a13b)


删除后
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/42687631/44897a95-75a7-43a4-9c6b-642adaf93b14)


下拉刷新时
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/42687631/2dcae721-1ec6-4246-b17e-26da92aa6790)


下拉刷新完
![image](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/42687631/44ed26bd-3c0b-445c-8354-2af4a1559002)
