### ISSUE TITLE
作者，支持 API9吗

### ISSUE THREAD

**Issue by JoeBaiBai** [AbnerMing888/HarmonyOsRefresh#8]

**Comment by AbnerMing888** [comment]
以前是支持的，目前鸿蒙是基于NEXT的，所以就废弃了，因为NEXT和Api9还是有很大差异的，Api9很多在NEXT是无法使用的，建议：趁早升级NEXT

**Comment by 529523346** [comment]
next怎么申请哦，现在官网开放的还是api9，好多库确都是大于9[破涕为笑]

**Comment by 529523346** [comment]
> [AbnerMing888](/AbnerMing888)

大佬，next怎么申请哦，现在官网开放的还是api9，好多库确都是大于9[破涕为笑]

**Comment by AbnerMing888** [comment]
个人不好申请，让公司出面去申请，比较好通过

**Comment by 529523346** [comment]
> 个人不好申请，让公司出面去申请，比较好通过

嗯嗯，已经通过朋友公司的账号尝鲜了，感谢指点

**Comment by jlu-v8m** [comment]
@529523346 请问如何申请啊？官网没找了没找到入口...
申请后就可以使用这个库了么？

遇到的问题：ERROR: The compatibleSdkVersion 9 cannot be smaller than version 40100011 declared in library [:refresh] 
 as the library might be using APIS not available in 9

**Comment by 529523346** [comment]
> @529523346 请问如何申请啊？官网没找了没找到入口... 申请后就可以使用这个库了么？
> 
> 遇到的问题：ERROR: The compatibleSdkVersion 9 cannot be smaller than version 40100011 declared in library [:refresh] as the library might be using APIS not available in 9
是的，申请后就能用api11，不申请也能用这个库，配置改成
    "@ohos/pulltorefresh": "2.0.1",
就行，用低版本的
