### ISSUE TITLE
有几个问题，望修复

### ISSUE THREAD

**Issue by jikanghui** [AbnerMing888/HarmonyOsRefresh#84]
1.enableRefresh和enableLoadMore值有时需要动态改变，比如分页加载完成后，需要禁止加载更多，值变成false后会显示出半个刷新头组件
2.loadingLayout显示的时候应该禁止滑动
3.finishRefresh和finishLoadMore内部未判断当前组件是否正在加载中，未在加载中调用，会突然出现一下动画
![微信截图_20240715155253](https://github.com/user-attachments/assets/110df9ad-7d4f-47b8-ac33-db85266ee697)

**Comment by AbnerMing888** [comment]
您好，您的问题已关注

**Comment by artillerymans** [comment]
我看更新了版本 1.3.0，头部刷新的问题貌似没有复现了，但是底部会有数据展示不全
