### ISSUE TITLE
slideRightMenuLayout属性问题

### ISSUE THREAD

**Issue by longrenkai** [AbnerMing888/HarmonyOsRefresh#85]
我想做一个右滑删除，但是不想用swipeRightMenuLayout因为会导致可以左右都可以滑动，但是slideRightMenuLayout无法将它的高度自适应，请问有什么解决办法？

**Comment by longrenkai** [comment]
通过设置右侧删除按钮align属性可以做到高度拉伸，但是因为设置了每个item的margin，导致拉伸后的高度延伸到margin处了，虽然可以通过自定义一个父容器然后设置padding可以规避，但是仍然不是最优解，希望可以设置每个ListItem的间距，看了源码，没有设置间距。
今天又发现一个问题：右滑删除，然后删除了该数据后，refresh，结果删除按钮依然还在之前删除的索引上，看能不能在每次reloadData，或者notifyDataReload后将右滑消失，或者将方法提供出来，可以手动关闭右滑。
还有，是否能将ets的源码放出来啊？现在只能根据js打包后的源码来看。

**Comment by AbnerMing888** [comment]
您好，您的问题已关注

**Comment by longrenkai** [comment]
我们有这样的需求，在item左滑时显示出删除按钮在此如果点击删除或者再次左滑则删除该item，该如何去做？

**Comment by longrenkai** [comment]
ListView是否能添加一个尾部的builder？用于展示没有数据了或者其他的自定义的builder

**Comment by AbnerMing888** [comment]
尾部，这个功能我已添加，下个版本可以使用，侧滑问题，我再看

**Comment by longrenkai** [comment]
下拉刷新列表-finishRefresh()或者finishLoadMore()之后-将enableRefresh 或者 enableLoadMore设置为false，会导致头部或者尾部隐藏的动画关闭，因为隐藏动画还在播放-从而只隐藏了一半导致UI展示错误，看能不能在设置enableRefresh不直接控制头部的显示，让隐藏动画关闭之后再控制其关闭效果

**Comment by longrenkai** [comment]
请问新版本解决了侧滑的问题吗？
