### ISSUE TITLE
enableRefresh 禁用刷新后，整个列表向上偏移了

### ISSUE THREAD

**Issue by XiongZP** [AbnerMing888/HarmonyOsRefresh#86]
![image](https://github.com/user-attachments/assets/1d0763e3-2057-48ed-94db-358be8d9c712)

**Comment by XiongZP** [comment]
![image](https://github.com/user-attachments/assets/b5837b25-d140-48f8-ac7d-aa14e81fe259)

**Comment by XiongZP** [comment]
已解决

**Comment by AbnerMing888** [comment]
好的，我从新做了优化，可以在下一个版本再次做下验证
