### ISSUE TITLE
如何在顶部添加多一个 基于 ListView 的 HeaderView?

### ISSUE THREAD

**Issue by chen570075003** [AbnerMing888/HarmonyOsRefresh#87]
如图所示，请教一下如何实现这种视图，不同于Group的 Header。
<img width="890" alt="image" src="https://github.com/user-attachments/assets/84bf8799-affd-419d-9d78-3318f041b034">

**Comment by AbnerMing888** [comment]
itemHeaderLayout，支持自定义视图，你可以在视图里进行实现
