### ISSUE TITLE
ListView懒加载模式，数据刷新问题

### ISSUE THREAD

**Issue by drowtram** [AbnerMing888/HarmonyOsRefresh#9]
<img width="969" alt="image" src="https://github.com/AbnerMing888/HarmonyOsRefresh/assets/4158890/a4fbb645-0068-4922-ba45-0d35f344f9f2">
如图，我在请求接口获取到数据时，会根据pageNo判断是刷新还是加载更多，如果是刷新，我需要清空掉历史数据，重新添加新数据，目前发现没有提供api去删除全部列表数据，我只能调用getDataAll去迭代删除所有数据，但是最后展示有问题

具体问题就是是：每次下拉刷新，数据列表都会增加一页的数据，而不是只展示第一页的数据，且后面的数据在layout时，itemLayout传递过来的item为undefined，这就导致显示有问题。

效果如下：
![Screenshot_20240510172213218](https://github.com/AbnerMing888/HarmonyOsRefresh/assets/4158890/8210adcd-2e6f-4987-a329-03ef96e9d4ed)

麻烦帮忙看下是否是我调用的方式不对还是别的什么问题？
版本是：abner/refresh(V1.0.5)
鸿蒙API：11

**Comment by AbnerMing888** [comment]
关于懒加载还有普通数据之间的操作，我重新做了梳理，今天已经提交，请关注1.0.7版本
操作代码案例如下，可关注Demo中的LazyDataOperationPage和DataOperationPage两个页面实例。

switch (index) {
          case 0: //增加一个
            _this.dataSource.pushData(100)
            break;
          case 1: //指定位置增加一个
            _this.dataSource.pushDataPosition(2, 200)
            break;
          case 2: //数组添加
            _this.dataSource.pushDataArray([300, 301, 302])
            break;
          case 3: //可变参数形式添加
            _this.dataSource.pushDataVariable(400, 401, 402)
            break;
          case 4: //删除第一个
            _this.dataSource.deleteFirst()
            break;
          case 5: //删除最后一个
            _this.dataSource.deleteLast()
            break;
          case 6: //删除指定一个
            _this.dataSource.deleteData(2)
            break;
          case 7: //删除全部
            _this.dataSource.deleteAll()
            break;
          case 8: //修改数据
            _this.dataSource.changeData(3, 9999)
            break;
        }
