### ISSUE TITLE
ListView 不支持设置.lanes(2) 属性？

### ISSUE THREAD

**Issue by loveliveis** [AbnerMing888/HarmonyOsRefresh#91]
目前使用发现ListView 并不能支持设置lanes 属性，希望能支持下

**Comment by AbnerMing888** [comment]
请在下个版本验证，在ListAttr增加了两个属性
lanesValue?: number | LengthConstrain
lanesGutter?: Dimension

**Comment by Cocobboy** [comment]
lanesValue 无法适配一多，折叠屏 动态改变lanes 列表刷新
