### ISSUE TITLE
自定义loadingMore放gif图会出现加载不出来的问题

### ISSUE THREAD

**Issue by longrenkai** [AbnerMing888/HarmonyOsRefresh#94]
当我自定义footerLoadLayout  当status为loading时 放gif图展示不出来，在其他状态却能展示，GIF图我是直接从你的模块里copy了一个出来的。

**Comment by longrenkai** [comment]
发现好像跟loadMoreFooterAttribute 的height有关  足够高的话，展示gif图就能成功，设置小了就展示不出来

**Comment by AbnerMing888** [comment]
自定义刷新头和尾，都可以自己设置宽高
loadMoreFooterAttribute:(attr)=>{
         // attr.height = 
        },

**Comment by longrenkai** [comment]
我的意思是，如果attr.height高度设置的比较小 即使gif图尺寸更小也展示不出来那个gif图，需要设置200gif图放在容器的最上方才能展示出来，如果设置的height小的话，gif图不会展示，但是会预留宽高的位置，这个是什么情况？

**Comment by AbnerMing888** [comment]
这个问题需要研究，代码贴一下，我得看下
