### ISSUE TITLE
怎么监听onVisibleAreaChange

### ISSUE THREAD

**Issue by lisheng12311** [AbnerMing888/HarmonyOsRefresh#97]
能否添加onVisibleAreaChange的响应回调

**Comment by AbnerMing888** [comment]
好的，在属性里加了，请在1.3.2版本验证：
 listAttribute: (attr) => {
          attr.onVisibleAreaChange = (isVisible: boolean, currentRatio: number) => {
            //列表
          }
        },
        listItemAttribute: (attr) => {
          attr.onVisibleAreaChange = (position:number,isVisible: boolean, currentRatio: number) => {
            //列表条目
          }
        },

**Comment by lisheng12311** [comment]
已解决，谢谢

**Comment by lisheng12311** [comment]
已解决，谢谢
